# Generated by Django 5.2.6 on 2026-03-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
