# Generated by Django 5.2.6 on 2026-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_skills_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_json',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
