# Generated by Django 5.2.6 on 2026-01-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltrend',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
