# Generated by Django 5.2.6 on 2026-01-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_skilltrend_job_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('posted_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='demand_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='skilltrend',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltrend',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
