# Generated by Django 5.2.6 on 2026-01-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_alter_skill_demand_score_alter_skilltrend_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
