# Generated by Django 5.2.6 on 2026-01-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltrend',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
