# Generated by Django 5.2.6 on 2026-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_skilltrend_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltrend',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
