# Generated by Django 5.2.6 on 2026-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_skilltrend_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('technology_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('technology_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skilltrend',
            name='month',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='skilltrend',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
