# Generated by Django 5.2.6 on 2026-02-26 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_technology_remove_skill_id_skill_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltrend',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterUniqueTogether(
            name='skilltrend',
            unique_together={('skill', 'year', 'month')},
        ),
        migrations.AlterField(
            model_name='skilltrend',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='jobs.skill'),
        ),
        migrations.RemoveField(
            model_name='skilltrend',
            name='job',
        ),
    ]
