# Generated by Django 5.2.6 on 2026-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_skilltrend_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltrend',
            name='month',
            field=models.IntegerField(default=3),
        ),
    ]
