# Generated by Django 5.2.6 on 2026-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_skilltrend_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltrend',
            name='month',
            field=models.IntegerField(default=6),
        ),
    ]
