# Generated by Django 5.2.6 on 2026-02-17 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('users', '0002_remove_userprofile_id_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommender_date',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommender_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='technology',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_skills',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='skill_gap_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
