# Generated by Django 5.2.6 on 2026-02-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_recommendation_recommender_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='role',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user_skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
